## REST CLIENT 
GET http://localhost:8000/products/ HTTP/1.1 

### 
POST http://localhost:8000/products/ HTTP/1.1  
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4ODk4NjE2LCJpYXQiOjE3Njg4OTgzMTYsImp0aSI6IjZlNDAxODk5YmFjODRiNWY5ZTc0NjhiMDFmOGVlMTU4IiwidXNlcl9pZCI6IjQifQ.8PCYv2_VYETNTduQwMR6Pl3yMAodth_NK0V9l-zLzD8

{
    "name":"Television" , 
    "price":300.00 , 
    "stock":14,
    "description":"An amazing new TV"
}
### 
PATCH  http://localhost:8000/products/10/ HTTP/1.1  
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4ODk5ODcwLCJpYXQiOjE3Njg4OTk1NzAsImp0aSI6ImQ3MWUxZjM5MjNhMTQ5N2I4YTI4ZWI4OTc3NzM3MzhlIiwidXNlcl9pZCI6IjEifQ.ar-flHpnzf00yxzxvSz_zJ18EswC7QAX0Wc9wrEMN-k

{
    "name":"TV SAMSUNG" , 
    "price":300.00 , 
    "stock":14,
    "description":"An amazing new TV!"
}

### 
DELETE   http://localhost:8000/products/10/ HTTP/1.1  
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4ODk5ODcwLCJpYXQiOjE3Njg4OTk1NzAsImp0aSI6ImQ3MWUxZjM5MjNhMTQ5N2I4YTI4ZWI4OTc3NzM3MzhlIiwidXNlcl9pZCI6IjEifQ.ar-flHpnzf00yxzxvSz_zJ18EswC7QAX0Wc9wrEMN-k

### 
POST http://localhost:8000/api/token/ HTTP/1.1  
Content-Type: application/json 

{
    "username":"admin", 
    "password":"test"
}
### 
POST http://localhost:8000/api/token/refresh/ HTTP/1.1  
Content-Type: application/json 

{
    "refresh":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2ODk4NTQzMCwiaWF0IjoxNzY4ODk5MDMwLCJqdGkiOiJhYzVjNzQ2ZTYxNDg0N2E0Yjc5MWU3ZDljMjZjM2FiOCIsInVzZXJfaWQiOiI0In0.k8ETlYG3GM60l2dmVwy554zf7XcK4PF_Wl5OojAyYws"
}

### 
POST http://localhost:8000/order/ HTTP/1.1  
Content-Type: application/json 
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY5OTgzNjc4LCJpYXQiOjE3Njk5ODMzNzgsImp0aSI6ImYxYWNjOTY3MzBlOTQwYjg5NzVhNGNmZDgwMjU2YmYwIiwidXNlcl9pZCI6IjEifQ.lRs4ehIbupjJ1cNqlPFHfAPQ0FYujybnUMyGbe98YEw

{
   "status":"Pending" , 
   "user":1 , 
   "items":[
    {"product":500 , "quantity":3},
    {"product":612 , "quantity":2}
    ]
}